### PR TITLE
Adapt new behavior of System.console() since JDK22

### LINKED ISSUE #68: Adapt new behavior of System.console() since JDK22
Since [JDK22](https://inside.java/2023/07/31/quality-heads-up/):

> In JDK 22, System.console() has been changed to return a Console with enhanced editing features that improve the experience of programs that use the Console API. In addition, System.console() now returns a Console object when the standard streams are redirected or connected to a virtual terminal. Prior to JDK 22, System.console() instead returned null for these cases. This change may impact code that checks the return from System.console() to test if the JVM is connected to a terminal. If required, the -Djdk.console=java.base flag will restore the old behavior where the console is only returned when it is connected to a terminal. Starting JDK 22, one could also use the new Console.isTerminal() method to test if the console is connected to a terminal.

So, this check:

https://github.com/aeshell/aesh-readline/blob/d171b39f4eafe3afb5ac43359bb91d4472881d8c/readline/src/main/java/org/aesh/readline/terminal/TerminalBuilder.java#L146-L152

should be changed to:

    if (System.console() != null && System.console().isTerminal())

However, `isTerminal()` is a new method in JDK22. Alternatively, access ~~the private static method `Console::istty()`~~ `isTerminal` via reflection.

---

**Note:** Jansi crashes the JVM on initializing `org.fusesource.jansi.AnsiConsole` when `System.console().isTerminal()` is false. Related: https://github.com/quarkusio/quarkus/issues/39575

### PR DESCRIPTION
**Pull request by Eng-Fouad**
Resolves #68

### CODE REVIEW

File: readline/src/main/java/org/aesh/readline/terminal/TerminalBuilder.java [hunk 1]
```diff
@@ -156,4 +158,19 @@ private Terminal createWindowsTerminal(String name) throws IOException {
                     (out == null) ? System.out : out);
         }
     }
+
+    // Console.isTerminal() was introduced in Java 22
+    private static boolean isTerminal(Console console) {
+        try {
+            Method isTerminal = Console.class.getMethod("isTerminal");
```
Comment (gsmet) [inline readline/src/main/java/org/aesh/readline/terminal/TerminalBuilder.java:165]: Not sure if it's worth switching to a multi-versioned jar instead of relying on reflection + exception?

Comment (Eng-Fouad) [reply readline/src/main/java/org/aesh/readline/terminal/TerminalBuilder.java:165]: cc @stalep

Comment (stalep) [reply readline/src/main/java/org/aesh/readline/terminal/TerminalBuilder.java:168]: Hm, instead of reflection could we check if `Runtime.version() > 21` ?
Tbh, I'm not sure what's the "best" solution here, I'm open for anything. This method is usually not called more than once anyway...

Comment (Eng-Fouad) [reply readline/src/main/java/org/aesh/readline/terminal/TerminalBuilder.java:168]: Then the new method isTerminal won't compile on older JDKs (<= 21).

Comment (Eng-Fouad) [reply readline/src/main/java/org/aesh/readline/terminal/TerminalBuilder.java:168]: @gsmet @stalep Submitted an alternative PR that uses "multi-release jar" feature: #70

**Comment by Eng-Fouad** [comment]
@stalep @tristantarrant @karlll @jfdenise @iweiss

Could you please review this PR? It will fix this bug in Quarkus: https://github.com/quarkusio/quarkus/issues/39575

**Review by stalep — APPROVED** [review]

**Comment by stalep** [comment]
Thank for the pr @Eng-Fouad, sorry it took so long to get it merged!

**Comment by Eng-Fouad** [comment]
> Thank for the pr @Eng-Fouad, sorry it took so long to get it merged!

Thanks for accepting the PR. Will be there any new release soon?
